In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr.reshape((-1,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr.reshape((2,-1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr.reshape((1,8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [13]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [14]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.full((5,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [17]:
np.random.random((4,4))

array([[ 0.38188589,  0.91046177,  0.54996916,  0.80789646],
       [ 0.19073373,  0.40612474,  0.57341467,  0.05259901],
       [ 0.93938973,  0.59334446,  0.41234486,  0.77949591],
       [ 0.22252713,  0.72081311,  0.70535738,  0.97284395]])

# indexing

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])

In [11]:
arr = arr.reshape((3,4))

In [13]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr[-1,1:]

array([10, 11, 12])

In [15]:
arr[-2:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [19]:
arr[np.arange(3),np.arange(3)] -= 20

In [20]:
arr

array([[-19,   2,   3, -16],
       [  5, -14,   7, -12],
       [  9,  10,  -9,  -8]])

In [25]:
a2 = np.array([1,23,2,3,123,12],dtype = np.float64)

In [26]:
a2

array([   1.,   23.,    2.,    3.,  123.,   12.])

# math

In [28]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

In [29]:
b = np.array([[1,2,3,7],
              [4,5,6,9]])

In [31]:
a + a 

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [32]:
b - b + 1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
a.dot(b) #matrix multiplication

array([[ 9, 12, 15, 25],
       [19, 26, 33, 57],
       [29, 40, 51, 89]])

In [35]:
np.sum(a)

21

In [37]:
b

array([[1, 2, 3, 7],
       [4, 5, 6, 9]])

In [38]:
np.sum(b,axis=0) #col

array([ 5,  7,  9, 16])

In [39]:
np.sum(b, axis=1) #row

array([13, 24])

In [40]:
np.mean(b)

4.625

In [41]:
np.median(b)

4.5

In [42]:
np.random.uniform(1,22)

21.029600091133215

In [43]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.tile(a,(1,5))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])

In [46]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [47]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [7, 9]])

In [49]:
b.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [51]:
b.argsort(axis=0) #row

array([[0, 0, 0, 0],
       [1, 1, 1, 1]], dtype=int64)

In [52]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
b = np.array([555,555])

In [55]:
a + b # broadcast

array([[556, 557],
       [558, 559],
       [560, 561]])